### ISSUE TITLE
Issue with booking 

### ISSUE THREAD

**Issue by VladislavPavlov2310** [tramyardg/hotel-mgmt-system#16]
Hello, I have an issue with booking an existing room
<img width="1440" alt="Снимок экрана 2022-03-28 в 01 07 46" src="https://user-images.githubusercontent.com/61427973/160303044-967fd197-1862-491d-81b4-94f5251839d9.png">

**Comment by tramyardg** [comment]
it is maybe because the rsvp form is broken, it is showing NaN and undefined 
![image](https://user-images.githubusercontent.com/5623994/160324189-e2a6268b-982f-4f2a-8880-5a37ba3a050e.png)
