### ISSUE TITLE
How to access and use admin

### ISSUE THREAD

**Issue by VladislavPavlov2310** [tramyardg/hotel-mgmt-system#17]
How to access and use admin page even if I changed field on already registered user and entering url /admin.php I still get empy page like this
<img width="1440" alt="Снимок экрана 2022-03-28 в 01 11 28" src="https://user-images.githubusercontent.com/61427973/160303133-18d4971f-2a13-4378-bce7-754dd8f948f5.png">

**Comment by tramyardg** [comment]
@VladislavPavlov2310 check your database and find customer table, a customer is considered admin if the value of its ‘isadmin’ = 1
