### ISSUE TITLE
Access Admin Panel

### ISSUE THREAD

**Issue by vakandi** [tramyardg/hotel-mgmt-system#25]
Hi
Sorry to bother, i was wondering how to access to admin panel?
i setup everything, tried /app /admin.php etc..
Thanks in advance

**Comment by tramyardg** [comment]
What did you see when you try to access admin.php

**Comment by vakandi** [comment]
My bad i had a php issue + permission issue, fixed it by giving the apache2 user access to my folder & files + update the php + enable every php modules needed on apache2, now i can access the admin.php and the whole dashboard
Nice code by the way thanks for your fast responce !
