### ISSUE TITLE
Create admin field in customer table

### ISSUE THREAD

**Issue by tramyardg** [tramyardg/hotel-mgmt-system#6]
The problem was admin credentials are exposed in `admin.json`.  For security reason, we have to create a field in customer table to tell if the user is admin or not. Therefore, we don't need `admin.json` anymore for authenticating admins.

Files to modify:
- `hotel.sql`
- `app/models/Customer.php`: `isAdminSignedIn`

**Comment by AhmedHelalAhmed** [comment]
I can help

**Comment by tramyardg** [comment]
Sure no problem. Go ahead.

**Comment by AhmedHelalAhmed** [comment]
Review my pull request
